### PR TITLE
Documentation for translation and launch options

### PR DESCRIPTION
**Pull request by enriquesomolinos**

### CODE REVIEW

**Comment by 1Simo1** [comment]
Hi Enrique!

About "Modding" section (and so final result at game launch) : this feature for now is only for custom files loaded "as is" (like MENU.PAL) or works also for BPKs ?

**Comment by enriquesomolinos** [comment]
> Hi Enrique!
> 
> About "Modding" section (and so final result at game launch) : this feature for now is only for custom files loaded "as is" (like MENU.PAL) or works also for BPKs ?

I think it can work for bpk files too, I need to check it and I tell you tomorrow.

**Comment by 1Simo1** [comment]
Thanks for your quick reply 😁

**Comment by enriquesomolinos** [comment]
Added mod feature and doc

**Pull request merged**
